# GitHub Actions CI/CD Workflow for Xeref.ai

name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # Or your primary development branch, e.g., 'develop'

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify the Node.js version used in your project
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build
        env:
          # This allows Next.js to build without requiring all runtime env vars
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
          # Add other build-time environment variables here if needed

      # --- Deployment Steps ---
      # The following steps are placeholders. You will need to configure
      # authentication with Google Cloud by creating a Service Account and
      # adding its key as a secret in your GitHub repository.

      # - name: Authenticate with Google Cloud
      #   uses: 'google-github-actions/auth@v2'
      #   with:
      #     credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # - name: Deploy to Firebase Hosting
      #   uses: 'FirebaseExtended/action-hosting-deploy@v0'
      #   with:
      #     repoToken: '${{ secrets.GITHUB_TOKEN }}'
      #     firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
      #     channelId: live # Or a preview channel for non-main branches
      #     projectId: 'xerefai-prod' # Your Firebase project ID
